version: "2.2"

services:
  postgres:
    image: postgres:12.2
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
      - ./postgres_init.sh:/docker-entrypoint-initdb.d/postgres_init.sh
    environment:
      - POSTGRES_PASSWORD=debezium
      - POSTGRES_USER=debezium
      - POSTGRES_DB=debezium

  zookeeper:
    image: zookeeper:3.5.7
    hostname: zookeeper
    volumes:
      - ./storage/zk/data:/data
      - ./storage/zk/trxn:/datalog
    environment:
      - ZOO_MY_ID=1

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka
    volumes:
      - ./storage/kafka:/var/lib/kafka/data
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://127.0.0.1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper

  connect:
    image: cp-kafka-connect-debezium:5.5.0
    hostname: connect
    build:
      context: .
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: connect_debezium
      CONNECT_CONFIG_STORAGE_TOPIC: __connect_debezium_config
      CONNECT_CONFIG_STORAGE_PARTITIONS: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: __connect_debezium_offset
      CONNECT_OFFSET_STORAGE_PARTITIONS: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: __connect_debezium_status
      CONNECT_STATUS_STORAGE_PARTITIONS: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: 127.0.0.1
      CONNECT_REST_PORT: 8083
      CONNECT_PLUGIN_PATH: /usr/share/java
    depends_on:
      - postgres
